jobs:
- job: Job1
  displayName: Job-2 macOS Mojave
  pool:
    vmImage: "macOS-10.14"
  steps:
  - script: ls && uname 
    displayName: "checks system"

- job: Job2
  displayName: Job-2 macOS Catalina
  pool:
    vmImage: "macOS-latest"
  steps:
  - script: ls && uname 
    displayName: "checks system"