jobs:
- job: Job1
  displayName: Job-1 macOS
  pool:
    vmImage: "macos-latest"
  strategy:
    maxParallel: 2
    matrix: 
      Parallel_job_1:
        version: python2
      Parallel_job_2:
        version: python3
  steps:
    - script: pip install -r packages.json && pip3 install -r packages.json
      displayName: installs the necessary packages for Python2 and Python2
    - script: cd src && $(version) data.py
      displayName: "build with $(version)"
    - script: cd src && $(version) data.py
      displayName: "build with $(version)"

- job: Job2
  displayName: Job-2 Ubuntu
  pool:
    vmImage: "ubuntu-latest"
  strategy:
    maxParallel: 2
    matrix: 
      Parallel_job_1:
        version: python2
      Parallel_job_2:
        version: python3
  steps:
    - script: sudo apt install ttf-mscorefonts-installer
      displayName: installs the Times New Roman font
    - script: pip install -r packages.json && pip3 install -r packages.json
      displayName: installs the necessary packages for Python2 and Python2
    - script: cd src && $(version) data.py
      displayName: "build with $(version)"
    - script: cd src && $(version) data.py
      displayName: "build with $(version)"