strategy:
  parallel: 2
  # jobs:
  - job: Job1
    displayName: Job-2 macOS Mojave
    pool:
      vmImage: "macOS-10.14"
    steps:
    - script: ls && uname 
      displayName: "checks system"
    - script: python2 --version && python3 --version
      displayName: "checks Py VERSIONS"
    - script: brew update && brew upgrade
      displayName: "update the packages"
    - script: python2 --version && python3 --version
      displayName: "checks Py VERSIONS"


  - job: Job2
    displayName: Job-2 macOS Catalina
    pool:
      vmImage: "macOS-latest"
    steps:
    - script: ls && uname 
      displayName: "checks system"
    - script: python2 --version && python3 --version
      displayName: "checks Py VERSIONS"
    - script: brew update && brew upgrade
      displayName: "update the packages"
    - script: python2 --version && python3 --version
      displayName: "checks Py VERSIONS"