jobs:
# - job: Job1
#   displayName: Job-2 macOS Mojave
#   pool:
#     vmImage: "macOS-10.14"
#   strategy:
#     parallel: 2
#   steps:
#   - script: ls && uname 
#     displayName: "checks system"
#   - script: python2 --version && python3 --version
#     displayName: "checks Py VERSIONS"
#   - script: python2 --version && python3 --version
#     displayName: "checks Py VERSIONS"


# - job: Job2
#   displayName: Job-2 macOS Catalina
#   pool:
#     vmImage: "macOS-latest"
#   strategy:
#     parallel: 2
#   steps:
#   - script: ls && uname 
#     displayName: "checks system"
#   - script: python2 --version && python3 --version
#     displayName: "checks Py VERSIONS"
#   - script: python2 --version && python3 --version
#     displayName: "checks Py VERSIONS"

- job: Job3
  displayName: Job-3 Ubuntu
  pool:
    vmImage: "ubuntu-latest"
  strategy:
    maxParallel: 2
    matrix: 
      Parallel1job:
        version: python2
      Parallel2job:
        version: python3
  steps:
    - script: pip install -r packages.json && pip3 install -r packages.json
      displayName: installs the necessary packages
    - script: cd src && $(version) data.py
      displayName: build with py2
    - script: cd src && $(version) data.py
      displayName: build with py3