# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# trigger:
# - master
pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- script: sudo apt update
  displayName: 'Updates the image'
  
- script: sudo apt-get install -y python
  displayName: 'Installs python'

- script: sudo apt-get install -y python3
  displayName: 'Installs python3'

- script: ls
  displayName: 'where are we'

- script: python2 src/average.py
  displayName: 'runs the script'